var nif = {
  "input-weapon-2": "",
  "input-attack-2": "",
  "input-damage-2": "",
  "input-range-2": "",
  "input-ammo-2": "",
  "input-critical-2": "",
  "input-weapon-3": "",
  "input-attack-3": "",
  "input-damage-3": "",
  "input-range-3": "",
  "input-ammo-3": "",
  "input-critical-3": "",
  "input-race-class": "Elf Wizard",
  "clone-attack-count": 4,
  "clone-consumable-count": 4,
  "input-copper": "",
  "input-name": "Nif Amakir",
  "input-level": "6",
  "input-size": "Medium",
  "input-alignment": "Lawful Neutral",
  "input-xp": "23,264",
  "input-height": "6'0",
  "input-weight": "136 lbs",
  "input-age": "120 years",
  "input-gender": "Male",
  "input-speed": "30 feet, 6 squares",
  "input-initiative": "3",
  "input-platinum": "",
  "input-gold": "1,090",
  "input-silver": "",
  "input-hero-points": "2",
  "input-luck-points": "",
  "input-stat-str": "8",
  "input-stat-dex": "17",
  "input-stat-con": "14",
  "input-stat-int": "21",
  "input-stat-wis": "12",
  "input-stat-cha": "10",
  "input-stat-str-temp": "",
  "input-stat-dex-temp": "",
  "input-stat-con-temp": "",
  "input-stat-int-temp": "23",
  "input-stat-wis-temp": "",
  "input-stat-cha-temp": "",
  "input-body-slot-armor": "",
  "input-body-slot-belts": "",
  "input-body-slot-body": "",
  "input-body-slot-chest": "",
  "input-body-slot-eyes": "",
  "input-body-slot-feet": "",
  "input-body-slot-hands": "",
  "input-body-slot-head": "",
  "input-body-slot-headband": "Headband of Vast Intelligence +2",
  "input-body-slot-neck": "Amulet of Natural Armor +1",
  "input-body-slot-ring-left-hand": "Ring of Sustenance",
  "input-body-slot-ring-right-hand": "",
  "input-body-slot-shield": "",
  "input-body-slot-shoulders": "Cloak of Resistance +2",
  "input-body-slot-wrist": "",
  "input-consumable-1": "",
  "input-consumable-total-1": "",
  "input-consumable-used-1": "",
  "input-consumable-2": "",
  "input-consumable-total-2": "",
  "input-consumable-used-2": "",
  "input-consumable-3": "",
  "input-consumable-total-3": "",
  "input-consumable-used-3": "",
  "input-consumable-4": "",
  "input-consumable-total-4": "",
  "input-consumable-used-4": "",
  "input-hp": "42",
  "input-temp-hp": "",
  "input-current-hp": "42",
  "input-current-non-lethal-hp": "",
  "input-ac-misc": "",
  "input-ac-temp": "",
  "input-ac-flat-footed-misc": "",
  "input-ac-flat-footed-temp": "",
  "input-ac-touch-misc": "",
  "input-ac-touch-temp": "",
  "input-ac-armor": "",
  "input-ac-shield": "",
  "input-ac-deflect": "",
  "input-ac-dodge": "",
  "input-ac-natural": "1",
  "input-size-bonus": "",
  "input-fortitude-base": "2",
  "input-fortitude-racial": "",
  "input-fortitude-misc": "5",
  "input-fortitude-temp": "",
  "input-reflex-base": "2",
  "input-reflex-racial": "",
  "input-reflex-misc": "2",
  "input-reflex-temp": "",
  "input-will-base": "5",
  "input-will-racial": "",
  "input-will-misc": "2",
  "input-will-temp": "",
  "input-cmb-misc": "",
  "input-cmb-temp": "",
  "input-cmd-misc": "",
  "input-cmd-temp": "",
  "input-melee-attack-misc": "",
  "input-melee-attack-temp": "",
  "input-ranged-attack-misc": "",
  "input-ranged-attack-temp": "",
  "input-base-attack": "3",
  "input-special-size-bonus": "",
  "input-concentration": "11",
  "input-weapon-1": "",
  "input-attack-1": "",
  "input-damage-1": "",
  "input-range-1": "",
  "input-ammo-1": "",
  "input-critical-1": "",
  "input-weapon-4": "",
  "input-attack-4": "",
  "input-damage-4": "",
  "input-range-4": "",
  "input-ammo-4": "",
  "input-critical-4": "",
  "skill-acrobatics-ranks": "",
  "skill-acrobatics-misc": "",
  "skill-appraise-ranks": "4",
  "skill-appraise-misc": "3",
  "skill-bluff-ranks": "",
  "skill-bluff-misc": "",
  "skill-climb-ranks": "",
  "skill-climb-misc": "",
  "skill-craft-ranks": "",
  "skill-craft-misc": "",
  "skill-diplomacy-ranks": "",
  "skill-diplomacy-misc": "",
  "skill-disguise-ranks": "",
  "skill-disguise-misc": "",
  "skill-escape-artist-ranks": "",
  "skill-escape-artist-misc": "",
  "skill-fly-ranks": "",
  "skill-fly-misc": "",
  "skill-heal-ranks": "",
  "skill-heal-misc": "",
  "skill-intimidate-ranks": "",
  "skill-intimidate-misc": "",
  "skill-knowledge-arcana-ranks": "3",
  "skill-knowledge-arcana-misc": "3",
  "skill-knowledge-dungeoneering-ranks": "2",
  "skill-knowledge-dungeoneering-misc": "3",
  "skill-knowledge-engineering-ranks": "1",
  "skill-knowledge-engineering-misc": "3",
  "skill-knowledge-geography-ranks": "1",
  "skill-knowledge-geography-misc": "3",
  "skill-knowledge-history-ranks": "1",
  "skill-knowledge-history-misc": "3",
  "skill-knowledge-local-ranks": "1",
  "skill-knowledge-local-misc": "3",
  "skill-knowledge-nature-ranks": "1",
  "skill-knowledge-nature-misc": "3",
  "skill-knowledge-nobility-ranks": "1",
  "skill-knowledge-nobility-misc": "3",
  "skill-knowledge-planes-ranks": "3",
  "skill-knowledge-planes-misc": "3",
  "skill-knowledge-religion-ranks": "3",
  "skill-knowledge-religion-misc": "3",
  "skill-linguistics-ranks": "3",
  "skill-linguistics-misc": "3",
  "skill-perception-ranks": "6",
  "skill-perception-misc": "4",
  "skill-perform-ranks": "",
  "skill-perform-misc": "",
  "skill-ride-ranks": "",
  "skill-ride-misc": "",
  "skill-sense-motive-ranks": "6",
  "skill-sense-motive-misc": "2",
  "skill-spellcraft-ranks": "6",
  "skill-spellcraft-misc": "3",
  "skill-stealth-ranks": "",
  "skill-stealth-misc": "",
  "skill-survival-ranks": "",
  "skill-survival-misc": "",
  "skill-swim-ranks": "",
  "skill-swim-misc": "",
  "skill-use-magic-device-ranks": "6",
  "skill-use-magic-device-misc": "",
  "input-spells-known-level-0": "",
  "input-spells-daily-level-0": "4",
  "input-spell-dc-level-0": "16",
  "input-spells-known-level-1": "",
  "input-spells-daily-level-1": "5",
  "input-spell-dc-level-1": "17",
  "input-spells-known-level-2": "",
  "input-spells-daily-level-2": "4",
  "input-spell-dc-level-2": "18",
  "input-spells-known-level-3": "",
  "input-spells-daily-level-3": "3",
  "input-spell-dc-level-3": "19",
  "input-spells-known-level-4": "",
  "input-spells-daily-level-4": "",
  "input-spell-dc-level-4": "",
  "input-spells-known-level-5": "",
  "input-spells-daily-level-5": "",
  "input-spell-dc-level-5": "",
  "input-spells-known-level-6": "",
  "input-spells-daily-level-6": "",
  "input-spell-dc-level-6": "",
  "input-spells-known-level-7": "",
  "input-spells-daily-level-7": "",
  "input-spell-dc-level-7": "",
  "input-spells-known-level-8": "",
  "input-spells-daily-level-8": "",
  "input-spell-dc-level-8": "",
  "input-spells-known-level-9": "",
  "input-spells-daily-level-9": "",
  "input-spell-dc-level-9": "",
  "spell-saved-bleed": "{\"name\":\"Bleed\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-erase": "{\"name\":\"Erase\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-daze": "{\"name\":\"Daze\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-disrupt-undead": "{\"name\":\"Disrupt Undead\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-touch-of-fatigue": "{\"name\":\"Touch of Fatigue\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-prestidigitation": "{\"name\":\"Prestidigitation\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-light": "{\"name\":\"Light\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-ghost-sound": "{\"name\":\"Ghost Sound\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-spark": "{\"name\":\"Spark\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-acid-splash": "{\"name\":\"Acid Splash\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-mage-hand": "{\"name\":\"Mage Hand\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-flare": "{\"name\":\"Flare\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-detect-magic": "{\"name\":\"Detect Magic\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-detect-poison": "{\"name\":\"Detect Poison\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-dancing-lights": "{\"name\":\"Dancing Lights\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-mending": "{\"name\":\"Mending\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-arcane-mark": "{\"name\":\"Arcane Mark\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-message": "{\"name\":\"Message\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-ray-of-frost": "{\"name\":\"Ray of Frost\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-read-magic": "{\"name\":\"Read Magic\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-open-close": "{\"name\":\"Open Close\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-resistance": "{\"name\":\"Resistance\",\"level\":\"0\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-comprehend-languages": "{\"name\":\"Comprehend Languages\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-enlarge-person": "{\"name\":\"Enlarge Person\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-feather-fall": "{\"name\":\"Feather Fall\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-grease": "{\"name\":\"Grease\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-mage-armor": "{\"name\":\"Mage Armor\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-mount": "{\"name\":\"Mount\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-obscuring-mist": "{\"name\":\"Obscuring Mist\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-protection-from-chaos": "{\"name\":\"Protection from Chaos\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-protection-from-evil": "{\"name\":\"Protection from Evil\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-shield": "{\"name\":\"Shield\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-summon-monster-i": "{\"name\":\"Summon Monster I\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-unseen-servant": "{\"name\":\"Unseen Servant\",\"level\":\"1\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-blur": "{\"name\":\"Blur\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-create-pit": "{\"name\":\"Create Pit\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-flaming-sphere": "{\"name\":\"Flaming Sphere\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-glitterdust": "{\"name\":\"Glitterdust\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-invisibility": "{\"name\":\"Invisibility\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-levitate": "{\"name\":\"Levitate\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-mirror-image": "{\"name\":\"Mirror Image\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-resist-energy": "{\"name\":\"Resist Energy\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-stone-call": "{\"name\":\"Stone Call\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-summon-monster-ii": "{\"name\":\"Summon Monster II\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-web": "{\"name\":\"Web\",\"level\":\"2\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-stinking-cloud": "{\"name\":\"Stinking Cloud\",\"level\":\"3\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-summon-monster-iii": "{\"name\":\"Summon Monster III\",\"level\":\"3\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-spiked-pit": "{\"name\":\"Spiked Pit\",\"level\":\"3\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-aqueous-orb": "{\"name\":\"Aqueous Orb\",\"level\":\"3\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-fly": "{\"name\":\"Fly\",\"level\":\"3\",\"prepared\":0,\"active\":false,\"cast\":0}",
  "spell-saved-sleet-storm": "{\"name\":\"Sleet Storm\",\"level\":\"3\",\"prepared\":0,\"active\":false,\"cast\":0}"
};
