var spellsData = (function() {

  var _all_spellsObject = null;

  var _all_spellName = [
    "Acid Arrow",
    "Acid Fog",
    "Acid Splash",
    "Aid",
    "Air Walk",
    "Align Weapon",
    "Alter Self",
    "Alarm",
    "Analyze Dweomer",
    "Animal Growth",
    "Animal Messenger",
    "Animal Shapes",
    "Animal Trance",
    "Animate Dead",
    "Animate Objects",
    "Animate Plants",
    "Animate Rope",
    "Antilife Shell",
    "Antimagic Field",
    "Antipathy",
    "Antiplant Shell",
    "Arcane Eye",
    "Arcane Lock",
    "Arcane Mark",
    "Arcane Sight",
    "Arcane Sight, Greater",
    "Astral Projection",
    "Atonement",
    "Augury",
    "Awaken",
    "Bane",
    "Banishment",
    "Barkskin",
    "Bear's Endurance",
    "Bear's Endurance, Mass",
    "Beast Shape I",
    "Beast Shape II",
    "Beast Shape III",
    "Beast Shape IV",
    "Bestow Curse",
    "Binding",
    "Black Tentacles",
    "Blade Barrier",
    "Blasphemy",
    "Bleed",
    "Bless",
    "Bless Water",
    "Bless Weapon",
    "Blight",
    "Blindness/Deafness",
    "Blink",
    "Blur",
    "Break Enchantment",
    "Breath Of Life",
    "Bull's Strength",
    "Bull's Strength, Mass",
    "Burning Hands",
    "Call Lightning",
    "Call Lightning Storm",
    "Calm Animals",
    "Calm Emotions",
    "Cat's Grace",
    "Cat's Grace, Mass",
    "Cause Fear",
    "Chain Lightning",
    "Changestaff",
    "Chaos Hammer",
    "Charm Person",
    "Charm Animal",
    "Charm Monster",
    "Charm Monster, Mass",
    "Chill Metal",
    "Chill Touch",
    "Circle Of Death",
    "Clairaudience/Clairvoyance",
    "Clenched Fist",
    "Cloak of Chaos",
    "Clone",
    "Cloudkill",
    "Color Spray",
    "Command",
    "Command, Greater",
    "Command Plants",
    "Command Undead",
    "Commune",
    "Commune with Nature",
    "Comprehend Languages",
    "Cone of Cold",
    "Confusion",
    "Confusion, Lesser",
    "Consecrate",
    "Contact Other Plane",
    "Contagion",
    "Contingency",
    "Continual Flame",
    "Control Plants",
    "Control Undead",
    "Control Water",
    "Control Weather",
    "Control Winds",
    "Create Food and Water",
    "Create Undead",
    "Create Greater Undead",
    "Create Water",
    "Creeping Doom",
    "Crushing Despair",
    "Crushing Hand",
    "Cure Light Wounds",
    "Cure Critical Wounds",
    "Cure Light Wounds, Mass",
    "Cure Critical Wounds, Mass",
    "Cure Moderate Wounds",
    "Cure Moderate Wounds, Mass",
    "Cure Serious Wounds",
    "Cure Serious Wounds, Mass",
    "Curse Water",
    "Dancing Lights",
    "Darkness",
    "Darkvision",
    "Daylight",
    "Daze",
    "Daze Monster",
    "Death Knell",
    "Death Ward",
    "Deathwatch",
    "Deeper Darkness",
    "Deep Slumber",
    "Delayed Blast Fireball",
    "Delay Poison",
    "Demand",
    "Desecrate",
    "Destruction",
    "Detect Animals or Plants",
    "Detect Chaos",
    "Detect Evil",
    "Detect Good",
    "Detect Law",
    "Detect Magic",
    "Detect Poison",
    "Detect Scrying",
    "Detect Secret Doors",
    "Detect Snares and Pits",
    "Detect Thoughts",
    "Detect Undead",
    "Dictum",
    "Dimensional Anchor",
    "Dimensional Lock",
    "Dimension Door",
    "Diminish Plants",
    "Discern Lies",
    "Discern Location",
    "Disguise Self",
    "Disintegrate",
    "Dismissal",
    "Dispel Chaos",
    "Dispel Evil",
    "Dispel Good",
    "Dispel Law",
    "Dispel Magic",
    "Dispel Magic, Greater",
    "Displacement",
    "Disrupting Weapon",
    "Disrupt Undead",
    "Divination",
    "Divine Favor",
    "Divine Power",
    "Dominate Animal",
    "Dominate Monster",
    "Dominate Person",
    "Doom",
    "Dream",
    "Eagle's Splendor",
    "Eagle's Splendor, Mass",
    "Earthquake",
    "Elemental Body I",
    "Elemental Body II",
    "Elemental Body III",
    "Elemental Body IV",
    "Elemental Swarm",
    "Endure Elements",
    "Energy Drain",
    "Enervation",
    "Enlarge Person",
    "Enlarge Person, Mass",
    "Entangle",
    "Enthrall",
    "Entropic Shield",
    "Erase",
    "Ethereal Jaunt",
    "Etherealness",
    "Expeditious Retreat",
    "Explosive Runes",
    "Eyebite",
    "Fabricate",
    "Faerie Fire",
    "False Life",
    "False Vision",
    "Feather Fall",
    "Feeblemind",
    "Find the Path",
    "Find Traps",
    "Finger Of Death",
    "Fire Shield",
    "Fire Seeds",
    "Fire Storm",
    "Fire Trap",
    "Fireball",
    "Flame Arrow",
    "Flame Blade",
    "Flame Strike",
    "Flaming Sphere",
    "Flare",
    "Flesh to Stone",
    "Floating Disk",
    "Fly",
    "Fog Cloud",
    "Forbiddance",
    "Forcecage",
    "Forceful Hand",
    "Foresight",
    "Form of the Dragon I",
    "Form of the Dragon II",
    "Form of the Dragon III",
    "Fox's Cunning",
    "Fox's Cunning, Mass",
    "Freedom",
    "Freedom of Movement",
    "Freezing Sphere",
    "Gaseous Form",
    "Gate",
    "Geas/Quest",
    "Geas, Lesser",
    "Gentle Repose",
    "Ghost Sound",
    "Ghoul touch",
    "Giant Form I",
    "Giant Form II",
    "Giant Vermin",
    "Glibness",
    "Glitterdust",
    "Globe of Invulnerability, Lesser",
    "Globe Of Invulnerability",
    "Glyph Of Warding",
    "Glyph of Warding, Greater",
    "Goodberry",
    "Good Hope",
    "Grasping Hand",
    "Grease",
    "Guards and Wards",
    "Guidance",
    "Gust Of Wind",
    "Hallow",
    "Hallucinatory Terrain",
    "Halt Undead",
    "Harm",
    "Haste",
    "Heal",
    "Heal, Mass",
    "Heal Mount",
    "Heat Metal",
    "Helping Hand",
    "Heroes' Feast",
    "Heroism",
    "Heroism, Greater",
    "Hide from Animals",
    "Hide from Undead",
    "Hideous Laughter",
    "Hold Person",
    "Hold Monster",
    "Hold Monster, Mass",
    "Hold Person, Mass",
    "Hold Portal",
    "Holy Aura",
    "Holy Smite",
    "Holy Sword",
    "Holy Word",
    "Horrid Wilting",
    "Hypnotic Pattern",
    "Hypnotism",
    "Ice Storm",
    "Identify",
    "Illusory Script",
    "Illusory Wall",
    "Imbue with Spell Ability",
    "Implosion",
    "Imprisonment",
    "Incendiary Cloud",
    "Inflict Light Wounds",
    "Inflict Critical Wounds",
    "Inflict Critical Wounds, Mass",
    "Inflict Light Wounds, Mass",
    "Inflict Moderate Wounds",
    "Inflict Moderate Wounds, Mass",
    "Inflict Serious Wounds",
    "Inflict Serious Wounds, Mass",
    "Insanity",
    "Interposing Hand",
    "Invisibility",
    "Invisibility, Greater",
    "Invisibility, Mass",
    "Invisibility Purge",
    "Invisibility Sphere",
    "Iron Body",
    "Ironwood",
    "Irresistible Dance",
    "Jump",
    "Keen Edge",
    "Knock",
    "Know Direction",
    "Legend Lore",
    "Levitate",
    "Light",
    "Lightning Bolt",
    "Limited Wish",
    "Liveoak",
    "Locate Object",
    "Locate Creature",
    "Longstrider",
    "Lullaby",
    "Mage Armor",
    "Mage Hand",
    "Mage's Disjunction",
    "Mage's Faithful Hound",
    "Mage's Lucubration",
    "Mage's Magnificent Mansion",
    "Mage's Private Sanctum",
    "Mage's Sword",
    "Magic Aura",
    "Magic Circle against Evil",
    "Magic Circle against Chaos",
    "Magic Circle against Good",
    "Magic Circle against Law",
    "Magic Fang",
    "Magic Fang, Greater",
    "Magic Jar",
    "Magic Missile",
    "Magic Mouth",
    "Magic Stone",
    "Magic Vestment",
    "Magic Weapon",
    "Magic Weapon, Greater",
    "Minor Creation",
    "Major Creation",
    "Major Image",
    "Make Whole",
    "Mark of Justice",
    "Maze",
    "Meld into Stone",
    "Mending",
    "Message",
    "Meteor Swarm",
    "Mind Blank",
    "Mind Fog",
    "Minor Image",
    "Miracle",
    "Mirage Arcana",
    "Mirror Image",
    "Misdirection",
    "Mislead",
    "Mnemonic Enhancer",
    "Modify Memory",
    "Moment of Prescience",
    "Mount",
    "Move Earth",
    "Neutralize Poison",
    "Nightmare",
    "Nondetection",
    "Obscure Object",
    "Obscuring Mist",
    "Open/Close",
    "Order's Wrath",
    "Overland Flight",
    "Owl's Wisdom",
    "Owl's Wisdom, Mass",
    "Passwall",
    "Pass without Trace",
    "Permanency",
    "Permanent Image",
    "Persistent Image",
    "Phantasmal Killer",
    "Phantom Steed",
    "Phantom Trap",
    "Phase Door",
    "Planar Ally, Lesser",
    "Planar Ally",
    "Planar Ally, Greater",
    "Planar Binding, Lesser",
    "Planar Binding",
    "Planar Binding, Greater",
    "Plane Shift",
    "Plant Growth",
    "Plant Shape I",
    "Plant Shape II",
    "Plant Shape III",
    "Poison",
    "Polar Ray",
    "Polymorph",
    "Polymorph, Greater",
    "Polymorph Any Object",
    "Power Word Blind",
    "Power Word Kill",
    "Power Word Stun",
    "Prayer",
    "Prestidigitation",
    "Prismatic Sphere",
    "Prismatic Spray",
    "Prismatic Wall",
    "Prying Eyes, Greater",
    "Produce Flame",
    "Programmed Image",
    "Project Image",
    "Protection From Arrows",
    "Protection From Chaos",
    "Protection From Evil",
    "Protection From Good",
    "Protection From Law",
    "Protection from Spells",
    "Purify Food and Drink",
    "Pyrotechnics",
    "Quench",
    "Rage",
    "Rainbow Pattern",
    "Raise Dead",
    "Ray Of Enfeeblement",
    "Ray of Exhaustion",
    "Ray of Frost",
    "Read Magic",
    "Reduce Person",
    "Reduce Animal",
    "Reduce Person, Mass",
    "Refuge",
    "Regenerate",
    "Reincarnate",
    "Remove Blindness/Deafness",
    "Remove Curse",
    "Remove Disease",
    "Remove Fear",
    "Remove Paralysis",
    "Repel Metal or Stone",
    "Repel Vermin",
    "Repel Wood",
    "Repulsion",
    "Resilient Sphere",
    "Resistance",
    "Resist Energy",
    "Restoration",
    "Restoration, Greater",
    "Restoration, Lesser",
    "Resurrection",
    "Reverse Gravity",
    "Righteous Might",
    "Rope Trick",
    "Rusting Grasp",
    "Sanctuary",
    "Scare",
    "Scintillating Pattern",
    "Scorching Ray",
    "Screen",
    "Scrying",
    "Scrying, Greater",
    "Sculpt Sound",
    "Searing Light",
    "Secret Chest",
    "Secret Page",
    "Secure Shelter",
    "See Invisibility",
    "Seeming",
    "Sending",
    "Sepia Snake Sigil",
    "Sequester",
    "Shadow Conjuration",
    "Shades",
    "Shadow Conjuration, Greater",
    "Shadow Evocation",
    "Shadow Evocation, Greater",
    "Shadow Walk",
    "Shambler",
    "Shapechange",
    "Shatter",
    "Shield",
    "Shield Of Faith",
    "Shield of Law",
    "Shield Other",
    "Shillelagh",
    "Shrink Item",
    "Shocking Grasp",
    "Shout",
    "Shout, Greater",
    "Silence",
    "Silent Image",
    "Simulacrum",
    "Slay Living",
    "Sleep",
    "Sleet Storm",
    "Slow",
    "Snare",
    "Soften Earth and Stone",
    "Solid Fog",
    "Song of Discord",
    "Soul Bind",
    "Sound Burst",
    "Speak with Animals",
    "Speak with Dead",
    "Speak with Plants",
    "Spectral Hand",
    "Spell Immunity",
    "Spell Immunity, Greater",
    "Spell Resistance",
    "Spellstaff",
    "Spell Turning",
    "Spider Climb",
    "Spike Growth",
    "Spike Stones",
    "Spiritual Weapon",
    "Stabilize",
    "Statue",
    "Status",
    "Stinking Cloud",
    "Stone Shape",
    "Stoneskin",
    "Stone Tell",
    "Stone to Flesh",
    "Storm Of Vengeance",
    "Suggestion",
    "Suggestion, Mass",
    "Summon Instrument",
    "Summon Monster I",
    "Summon Monster II",
    "Summon Monster III",
    "Summon Monster IV",
    "Summon Monster V",
    "Summon Monster VI",
    "Summon Monster VIII",
    "Summon Monster VII",
    "Summon Monster IX",
    "Summon Nature's Ally I",
    "Summon Nature's Ally II",
    "Summon Nature's Ally III",
    "Summon Nature's Ally IV",
    "Summon Nature's Ally V",
    "Summon Nature's Ally VI",
    "Summon Nature's Ally VII",
    "Summon Nature's Ally VIII",
    "Summon Nature's Ally IX",
    "Summon Swarm",
    "Sunbeam",
    "Sunburst",
    "Symbol of Death",
    "Symbol of Fear",
    "Symbol of Insanity",
    "Symbol of Pain",
    "Symbol of Persuasion",
    "Symbol of Sleep",
    "Symbol of Stunning",
    "Symbol Of Weakness",
    "Sympathetic Vibration",
    "Sympathy",
    "Telekinesis",
    "Telekinetic Sphere",
    "Telepathic Bond",
    "Teleport",
    "Teleport, Greater",
    "Teleport Object",
    "Teleportation Circle",
    "Temporal Stasis",
    "Time Stop",
    "Tiny Hut",
    "Tongues",
    "Touch of Fatigue",
    "Touch of Idiocy",
    "Transformation",
    "Transmute Metal to Wood",
    "Transmute Mud to Rock",
    "Transmute Rock to Mud",
    "Transport via Plants",
    "Trap the Soul",
    "Tree Shape",
    "Tree Stride",
    "True Resurrection",
    "True Seeing",
    "True Strike",
    "Undeath to Death",
    "Undetectable Alignment",
    "Unhallow",
    "Unholy Aura",
    "Unholy Blight",
    "Unseen Servant",
    "Vampiric Touch",
    "Veil",
    "Ventriloquism",
    "Virtue",
    "Vision",
    "Wail of the Banshee",
    "Wall Of Fire",
    "Wall Of Force",
    "Wall Of Ice",
    "Wall of Iron",
    "Wall Of Thorns",
    "Warp Wood",
    "Water Breathing",
    "Water Walk",
    "Waves of Exhaustion",
    "Waves of Fatigue",
    "Web",
    "Weird",
    "Whirlwind",
    "Whispering Wind",
    "Wind Walk",
    "Wind Wall",
    "Wish",
    "Wood Shape",
    "Word of Recall",
    "Word Of Chaos",
    "Zone of Silence",
    "Zone of Truth",
    "Wall Of Stone",
    "Agonize",
    "Hellfire Ray",
    "Sacrifice",
    "Burning Disarm",
    "Dweomer Retaliation",
    "Emergency Force Sphere",
    "Signifer's Rally",
    "Twine Double",
    "Fear",
    "Hold Animal",
    "Insect Plague",
    "Baleful Polymorph",
    "Prying Eyes",
    "Instant Summons",
    "Spellcasting Contract, Lesser",
    "Spellcasting Contract",
    "Spellcasting Contract, Greater",
    "Ancestral Communion",
    "Ancestral Gift",
    "Summon Ancestral Guardian",
    "See Through Stone",
    "Rune of Durability",
    "Rune of Warding",
    "Liberating Comand",
    "Suppres Charms and Compulsions",
    "Genius Avaricious",
    "Protection from Energy",
    "Retrieve Item",
    "Spherescry",
    "Illusory Poison",
    "Arcane Reinforcement",
    "Canopic Conversion",
    "Chastise",
    "Summon Elemental Steed",
    "Hibernate",
    "Sotto Voce",
    "Tomb Legion",
    "Tripvine",
    "Ape Walk",
    "Defoliate",
    "Heatstroke",
    "Swallow Your Fear",
    "Blood Rage",
    "Shield the Banner",
    "Vigor",
    "Absorbing Touch",
    "Accelerate Poison",
    "Acid Pit",
    "Alchemical Allocation",
    "Allfood",
    "Alter Winds",
    "Amplify Elixir",
    "Ant Haul",
    "Aqueous Orb",
    "Arcane Concordance",
    "Arrow Eruption",
    "Aspect of the Bear",
    "Aspect of the Falcon",
    "Aspect of the Stag",
    "Aspect of the Wolf",
    "Aura of Greater Courage",
    "Ball Lightning",
    "Banish Seeming",
    "Bard's Escape",
    "Beguiling Gift",
    "Bestow Grace",
    "Blaze of Glory",
    "Blessing Of Fervor",
    "Blessing of the Salamander",
    "Blood Biography",
    "Bloodhound",
    "Bloody Claws",
    "Bomber's Eye",
    "Borrow Fortune",
    "Borrow Skill",
    "Bow Spirit",
    "Brand",
    "Brand, Greater",
    "Break",
    "Brilliant Inspiration",
    "Bristle",
    "Burning Gaze",
    "Burst Bonds",
    "Cacophonous Call",
    "Cacophonous Call, Mass",
    "Calcific Touch",
    "Call Animal",
    "Campfire Wall",
    "Cast Out",
    "Castigate",
    "Castigate, Mass",
    "Challenge Evil",
    "Chameleon Stride",
    "Clashing Rocks",
    "Cleanse",
    "Cloak of Dreams",
    "Cloak of Shade",
    "Cloak of Winds",
    "Confess",
    "Contagious Flame",
    "Coordinated Effort",
    "Corruption Resistance",
    "Coward's Lament",
    "Crafter's Curse",
    "Crafter's Fortune",
    "Create Pit",
    "Create Treasure Map",
    "Cup Of Dust",
    "Dancing Lantern",
    "Deadly Finale",
    "Deafening Song Bolt",
    "Defile Armor",
    "Deflection",
    "Delayed Consumption",
    "Denounce",
    "Detect Aberration",
    "Detonate",
    "Devolution",
    "Discordant Blast",
    "Divine Transfer",
    "Divine Vessel",
    "Draconic Reservoir",
    "Dragon's Breath",
    "Dust Of Twilight",
    "Eagle Eye",
    "Elemental Aura",
    "Elemental Speech",
    "Elemental Touch",
    "Elude Time",
    "Enemy Hammer",
    "Enter Image",
    "Euphoric Tranquility",
    "Evolution Surge, Lesser",
    "Evolution Surge",
    "Evolution Surge, Greater",
    "Expeditious Excavation",
    "Expend",
    "Feast Of Ashes",
    "Feather Step",
    "Feather Step, Mass",
    "Fester",
    "Fester, Mass",
    "Fiery Body",
    "Fire Breath",
    "Fire of Entanglement",
    "Fire of Judgment",
    "Fire of Vengeance",
    "Fire Snake",
    "Firebrand",
    "Firefall",
    "Flames Of The Faithful",
    "Flare Burst",
    "Fluid Form",
    "Fly, Mass",
    "Foe to Friend",
    "Follow Aura",
    "Fool's Forbiddance",
    "Forced Repentance",
    "Frozen Note",
    "Gallant Inspiration",
    "Getaway",
    "Geyser",
    "Ghostbane Dirge",
    "Ghostbane Dirge, Mass",
    "Glide",
    "Grace",
    "Gravity Bow",
    "Grove of Respite",
    "Guiding Star",
    "Heroic Finale",
    "Hero's Defiance",
    "Hidden Speech",
    "Hide Campsite",
    "Holy Whisper",
    "Honeyed Tongue",
    "Hungry Pit",
    "Hydraulic Push",
    "Hydraulic Torrent",
    "Ill Omen",
    "Innocence",
    "Instant Armor",
    "Instant Enemy",
    "Invigorate",
    "Invigorate, Mass",
    "Jester's Jaunt",
    "Keen Senses",
    "King's Castle",
    "Knight's Calling",
    "Lead Blades",
    "Life Bubble",
    "Light Lance",
    "Lily Pad Stride",
    "Lockjaw",
    "Marks Of Forbiddance",
    "Mask Dweomer",
    "Memory Lapse",
    "Moonstruck",
    "Nap Stack",
    "Natural Rhythm",
    "Nature's Exile",
    "Negate Aroma",
    "Oath Of Peace",
    "Oracle's Burden",
    "Pain Strike",
    "Pain Strike, Mass",
    "Paladin's Sacrifice",
    "Phantasmal Revenge",
    "Phantasmal Web",
    "Pied Piping",
    "Pillar Of Life",
    "Planar Adaptation",
    "Planar Adaptation, Mass",
    "Pox Pustules",
    "Protective Spirit",
    "Purging Finale",
    "Purified Calling",
    "Putrefy Food and Drink",
    "Rally Point",
    "Rebuke",
    "Rampart",
    "Rejuvenate Eidolon, Lesser",
    "Rejuvenate Eidolon",
    "Rejuvenate Eidolon, Greater",
    "Resounding Blow",
    "Rest Eternal",
    "Restful Sleep",
    "Resurgent Transformation",
    "Retribution",
    "Reviving Finale",
    "Righteous Vigor",
    "River of Wind",
    "Sacred Bond",
    "Sacrificial Oath",
    "Saddle Surge",
    "Sanctify Armor",
    "Saving Finale",
    "Scent Trail",
    "Screech",
    "Sculpt Corpse",
    "Seamantle",
    "Seek Thoughts",
    "Share Language",
    "Shadow Projection",
    "Share Senses",
    "Shifting Sand",
    "Shared Wrath",
    "Sift",
    "Sirocco",
    "Sleepwalk",
    "Slipstream",
    "Snake Staff",
    "Solid Note",
    "Spark",
    "Spiked Pit",
    "Spiritual Ally",
    "Spite",
    "Stay the Hand",
    "Stone Call",
    "Stone Fist",
    "Stormbolts",
    "Strong Jaw",
    "Stumble Gap",
    "Stunning Finale",
    "Suffocation",
    "Suffocation, Mass",
    "Summon Eidolon",
    "Swarm Skin",
    "Thorn Body",
    "Threefold Aspect",
    "Thundering Drums",
    "Timely Inspiration",
    "Tireless Pursuit",
    "Tireless Pursuers",
    "Touch of Gracelessness",
    "Touch of the Sea",
    "Transmogrify",
    "Transmute Potion to Poison",
    "Treasure Stitching",
    "True Form",
    "Tsunami",
    "Twilight Knife",
    "Twin Form",
    "Unfetter",
    "Universal Formula",
    "Unwilling Shield",
    "Unwitting Ally",
    "Vanish",
    "Veil of Positive Energy",
    "Venomous Bolt",
    "Versatile Weapon",
    "Vomit Swarm",
    "Vortex",
    "Wake of Light",
    "Wall of Lava",
    "Wall of Suppression",
    "Wandering Star Motes",
    "Ward the Faithful",
    "Weapon of Awe",
    "Winds of Vengeance",
    "World Wave",
    "Wrath",
    "Wrathful Mantle",
    "Hunter's Eye",
    "Hunter's Howl",
    "Perceive Cues",
    "Residual Tracking",
    "Blessing of Courage and Life",
    "Rift of Ruin",
    "Constricting Coils",
    "Ancestral Memory",
    "Gorum's Armor",
    "Harrowing",
    "Infernal Healing",
    "Infernal Healing, Greater",
    "Lover's Vengeance",
    "Shield Of The Dawnflower",
    "Teleport Trap",
    "Unbreakable Heart",
    "Vision of Lamashtu",
    "Waters Of Lamashtu",
    "Trail of the Rose",
    "Acidic Spray",
    "Acute Senses",
    "Age Resistance, Lesser",
    "Age Resistance, Greater",
    "Age Resistance",
    "Allegro",
    "Animate Dead, Lesser",
    "Anthropomorphic Animal",
    "Anticipate Peril",
    "Arboreal Hammer",
    "Arcana Theft",
    "Archon's Aura",
    "Arrow of Law",
    "Ash Storm",
    "Astral Projection, Lesser",
    "Atavism",
    "Atavism, Mass",
    "Aura of Doom",
    "Badger's Ferocity",
    "Battlemind Link",
    "Bestow Grace of the Champion",
    "Blade of Bright Victory",
    "Blade of Dark Triumph",
    "Blessing of the Mole",
    "Blood Crow Strike",
    "Blood Mist",
    "Blood Transcription",
    "Boiling Blood",
    "Bungle",
    "Burrow",
    "Burst of Nettles",
    "Cackling Skull",
    "Call Construct",
    "Cape Of Wasps",
    "Caustic Eruption",
    "Chord Of Shards",
    "Circle Of Clarity",
    "Cold Ice Strike",
    "Compassionate Ally",
    "Conjure Black Pudding",
    "Contagion, Greater",
    "Control Construct",
    "Control Summoned Creature",
    "Corrosive Consumption",
    "Corrosive Touch",
    "Countless Eyes",
    "Create Demiplane",
    "Create Demiplane, Lesser",
    "Create Demiplane, Greater",
    "Curse, Major",
    "Curse Of Disgust",
    "Curse of Magic Negation",
    "Cursed Earth",
    "Cushioning Bands",
    "Dance of a Hundred Cuts",
    "Dance of a Thousand Cuts",
    "Darkvision, Greater",
    "Daze, Mass",
    "Decompose Corpse",
    "Defensive Shock",
    "Delay Pain",
    "Delusional Pride",
    "Diagnose Disease",
    "Disfiguring Touch",
    "Disguise Other",
    "Distracting Cacophony",
    "Distressing Tone",
    "Divine Pursuit",
    "Dread Bolt",
    "Eagle Aerie",
    "Ear-Piercing Scream",
    "Echolocation",
    "Eldritch Fever",
    "Envious Urge",
    "Epidemic",
    "Eruptive Pustules",
    "Excruciating Deformation",
    "Exquisite Accompaniment",
    "False Life, Greater",
    "Familiar Melding",
    "Fickle Winds",
    "Fleshworm Infestation",
    "Forbid Action",
    "Forbid Action, Greater",
    "Force Hook Charge",
    "Force Punch",
    "Forced Quiet",
    "Frigid Touch",
    "Frostbite",
    "Fumbletongue",
    "Fungal Infestation",
    "Ghostly Disguise",
    "Haunting Choir",
    "Haunting Mists",
    "Hex Ward",
    "Holy Ice",
    "Holy Shield",
    "Horn of Pursuit",
    "Howling Agony",
    "Ice Body",
    "Ice Crystal Teleport",
    "Icicle Dagger",
    "Icy Prison",
    "Icy Prison, Mass",
    "Imbue with Aura",
    "Interplanetary Teleport",
    "Interrogation",
    "Interrogation, Greater",
    "Joyful Rapture",
    "Ki Arrow",
    "Ki Leech",
    "Ki Shout",
    "Know The Enemy",
    "Leashed Shackles",
    "Lend Judgment",
    "Lend Judgment, Greater",
    "Lightning Arc",
    "Loathsome Veil",
    "Lunar Veil",
    "Mad Hallucination",
    "Mad Monkeys",
    "Malfunction",
    "Malicious Spite",
    "Marionette Possession",
    "Masterwork Transformation",
    "Miserable Pity",
    "Monstrous Physique I",
    "Monstrous Physique II",
    "Monstrous Physique III",
    "Monstrous Physique IV",
    "Murderous Command",
    "Oppressive Boredom",
    "Oracle's Vessel",
    "Orb Of The Void",
    "Overwhelming Grief",
    "Overwhelming Presence",
    "Pernicious Poison",
    "Persuasive Goad",
    "Piercing Shriek",
    "Plague Carrier",
    "Plague Storm",
    "Play Instrument",
    "Polar Midnight",
    "Polypurpose Panacea",
    "Possess Object",
    "Prediction of Failure",
    "Primal Scream",
    "Protective Penumbra",
    "Rain of Frogs",
    "Raise Animal Companion",
    "Rapid Repair",
    "Ray of Sickening",
    "Reckless Infatuation",
    "Remove Sickness",
    "Reprobation",
    "Resonating Word",
    "Restore Corpse",
    "Restore Eidolon",
    "Restore Eidolon, Lesser",
    "Ride the Lightning",
    "Ride The Waves",
    "Sanctify Corpse",
    "Sands of Time",
    "Scouring Winds",
    "Sculpt Simulacrum",
    "Serenity",
    "Shadowbard",
    "Shadow Step",
    "Shadow Weapon",
    "Shard of Chaos",
    "Share Memory",
    "Simulacrum, Lesser",
    "Skinsend",
    "Smug Narcissism",
    "Snapdragon Fireworks",
    "Sonic Thrust",
    "Soothe Construct",
    "Spear Of Purity",
    "Spit Venom",
    "Steal Voice",
    "Strangling Hair",
    "Summon Elder Worm",
    "Summon Froghemoth",
    "Summon Minor Ally",
    "Summon Minor Monster",
    "Surmount Affliction",
    "Symbol of Healing",
    "Symbol of Mirroring",
    "Symbol of Revelation",
    "Symbol of Scrying",
    "Symbol of Sealing",
    "Symbol of Slowing",
    "Symbol of Strife",
    "Symbol of Vulnerability",
    "Tar Ball",
    "Temporary Resurrection",
    "Terrible Remorse",
    "Touch of Slime",
    "Toxic Gift",
    "Transmute Blood To Acid",
    "Unadulterated Loathing",
    "Unbreakable Construct",
    "Undead Anatomy I",
    "Undead Anatomy II",
    "Undead Anatomy III",
    "Undead Anatomy IV",
    "Unholy Ice",
    "Unholy Sword",
    "Unnatural Lust",
    "Unprepared Combatant",
    "Unshakable Chill",
    "Utter Contempt",
    "Vengeful Outrage",
    "Vermin Shape I",
    "Vermin Shape II",
    "Vestment of the Champion",
    "Virtuoso Performance",
    "Vision of Hell",
    "Vitriolic Mist",
    "Vocal Alteration",
    "Volcanic Storm",
    "Wall of Sound",
    "Wartrain Mount",
    "Waves of Ecstasy",
    "Web Shelter",
    "Witness",
    "Wooden Phalanx",
    "Word of Resolve",
    "Youthful Appearance",
    "Staggering Fall",
    "Greensight",
    "Sheet Lightning",
    "Breeze",
    "Drench",
    "Jolt",
    "Penumbra",
    "Root",
    "Scoop",
    "Dazzling Blade",
    "Dazzling Blade, Mass",
    "Summon Accuser",
    "Summon Infernal Host",
    "Echean's Excellent Enclosure",
    "Ablative Sphere",
    "Burning Arc",
    "Snow Shape",
    "Summon Totem Creature",
    "Battering Blast",
    "Undeath Ward",
    "Silk To Steel",
    "Aram Zey's Focus",
    "Aram Zey's Trap Ward",
    "Bite the Hand",
    "Bite the Hand, Mass",
    "Corpse Lanterns",
    "Gilded Whispers",
    "Lipstitch",
    "Petulengro's Validation",
    "Sequester Thoughts",
    "Sharesister",
    "Stalwart Resolve",
    "Stolen Light",
    "Twisted Innards",
    "Blot",
    "Fire Sneeze",
    "Limp Lash",
    "Aroden's Spellbane",
    "Bladed Dash",
    "Bladed Dash, Greater",
    "Blast Barrier",
    "Call Weapon",
    "Crusader's Edge",
    "Eaglesoul",
    "Eldritch Conduit",
    "Eldritch Conduit, Greater",
    "Fleshcurdle",
    "Forceful Strike",
    "Geb's Hammer",
    "Geniekind",
    "Hungry Darkness",
    "Hunter's Lore",
    "Impart Mind",
    "Khain's Army",
    "Kiss of the First World",
    "Light of Iomedae",
    "Martial Marionette",
    "Martyr's Bargain",
    "Music of the Spheres",
    "Orchid's Drop",
    "Pugwampi's Grace",
    "Shadow Barbs",
    "Shining Cord",
    "Siphon Magic",
    "Song of Kyonin",
    "Spell Absorption",
    "Spell Absorption, Greater",
    "Spellscar",
    "Suppress Primal Magic",
    "Tattoo Potion",
    "Transfer Tattoo",
    "Vengeful Comets",
    "Vex Giant",
    "Weaponwand",
    "Zone of Foul Flames",
    "Ablative Barrier",
    "Absorb Toxicity",
    "Abundant Ammunition",
    "Adjuring Step",
    "Adoration",
    "Air Bubble",
    "Air Walk, Communal",
    "Animal Aspect",
    "Animal Aspect, Greater",
    "Ant Haul, Communal",
    "Arcane Cannon",
    "Bestow Weapon Proficiency",
    "Blistering Invective",
    "Bowstaff",
    "Brow Gasher",
    "Bullet Shield",
    "Burst of Speed",
    "Caging Bomb Admixture",
    "Certain Grip",
    "Chain of Perdition",
    "Companion Mind Link",
    "Compel Hostility",
    "Damp Powder",
    "Darkvision, Communal",
    "Daybreak Arrow",
    "Deadly Juggernaut",
    "Deadeye's Lore",
    "Debilitating Portent",
    "Delay Poison, Communal",
    "Destabilize Powder",
    "Discovery Torch",
    "Divine Arrow",
    "Dust Form",
    "Effortless Armor",
    "Endure Elements, Communal",
    "Energy Siege Shot",
    "Energy Siege Shot, Greater",
    "Fabricate Bullets",
    "Fiery Shuriken",
    "Find Quarry",
    "Flash Fire",
    "Forest Friend",
    "Frightful Aspect",
    "Frost Fall",
    "Haunted Fey Aspect",
    "Healing Thief",
    "Heroic Invocation",
    "Hostile Juxtaposition",
    "Hostile Juxtaposition, Greater",
    "Hostile Levitation",
    "Illusion of Calm",
    "Instrument of Agony",
    "Jolting Portent",
    "Judgment Light",
    "Jury-Rig",
    "Kinetic Reverberation",
    "Languid Bomb Admixture",
    "Liberating Command",
    "Life Conduit",
    "Life Conduit, Greater",
    "Life Conduit, Improved",
    "Lightning Lash Bomb Admixture",
    "Litany of Defense",
    "Litany Of Eloquence",
    "Litany of Entanglement",
    "Litany Of Escape",
    "Litany Of Madness",
    "Litany Of Righteousness",
    "Litany of Sight",
    "Litany of Sloth",
    "Litany of Thunder",
    "Litany Of Vengeance",
    "Litany of Warding",
    "Litany of Weakness",
    "Locate Weakness",
    "Lock Gaze",
    "Longshot",
    "Magic Siege Engine",
    "Magic Siege Engine, Greater",
    "Mask Dweomer, Communal",
    "Mind Blank, Communal",
    "Mirror Strike",
    "Moment of Greatness",
    "Mount, Communal",
    "Mutagenic Touch",
    "Named Bullet",
    "Named Bullet, Greater",
    "Negative Reaction",
    "Nondetection, Communal",
    "Obsidian Flow",
    "Peacebond",
    "Pellet Blast",
    "Phantom Chariot",
    "Phantom Driver",
    "Phantom Steed, Communal",
    "Pilfering Hand",
    "Protection from Arrows, Communal",
    "Protection from Chaos, Communal",
    "Protection from Energy, Communal",
    "Protection from Evil, Communal",
    "Protection from Good, Communal",
    "Protection from Law, Communal",
    "Pup Shape",
    "Qualm",
    "Recoil Fire",
    "Reinforce Armaments",
    "Reinforce Armaments, Communal",
    "Reloading Hands",
    "Resinous Skin",
    "Resist Energy, Communal",
    "Returning Weapon",
    "Returning Weapon, Communal",
    "Ricochet Shot",
    "See Alignment",
    "Shadow Bomb Admixture",
    "Share Language, Communal",
    "Shock Shield",
    "Shocking Image",
    "Siege Of Trees",
    "Siege of Trees, Greater",
    "Spell Immunity, Communal",
    "Spell Immunity, Greater Communal",
    "Spider Climb, Communal",
    "Spontaneous Immolation",
    "Stabilize Powder",
    "Stoneskin, Communal",
    "Summoner Conduit",
    "Sun Metal",
    "Symbol Of Striking",
    "Tactical Acumen",
    "Tar Pool",
    "Targeted Bomb Admixture",
    "Telekinetic Assembly",
    "Telekinetic Charge",
    "Terrain Bond",
    "Thunder Fire",
    "Tongues, Communal",
    "Touch Injection",
    "Twisted Space",
    "Unerring Weapon",
    "Viper Bomb Admixture",
    "Walk Through Space",
    "Warding Weapon",
    "Water Walk, Communal",
    "Weaken Powder",
    "Wilderness Soldiers",
    "Wreath of Blades",
    "Aspect of the Nightingale",
    "Vampiric Hunger",
    "Awaken the Devoured",
    "Charon's Dispensation",
    "Create Soul Gem",
    "Daemon Ward",
    "Death Knell Aura",
    "Death Knell Aura, Greater",
    "Lash of the Astradaemon",
    "Parasitic Soul",
    "Scourge of the Horsemen",
    "Soul Transfer",
    "Summon Cacodaemon",
    "Summon Cacodaemon, Greater",
    "Summon Ceustodaemon",
    "Summon Derghodaemon",
    "Summon Erodaemon",
    "Summon Meladaemon",
    "Summon Thanadaemon",
    "Call the Void",
    "Black Spot",
    "Salvage",
    "Skeleton Crew",
    "Track Ship",
    "Unseen Crew",
    "Advanced Scurvy",
    "Cloud Of Seasickness",
    "Submerge Ship",
    "Heroic Fortune",
    "Heroic Fortune, Mass",
    "Malediction",
    "Severed Fate",
    "Unravel Destiny",
    "Embrace Destiny",
    "Groundswell",
    "Ironbeard",
    "Toilsome Chant",
    "Blend",
    "Ward Of The Season",
    "Whispering Lore",
    "Death From Below",
    "Jitterbugs",
    "Major Phantom Object",
    "Minor Dream",
    "Minor Phantom Object",
    "Recharge Innate Magic",
    "Forgetful Slumber",
    "Paragon Surge",
    "Resilient Reservoir",
    "Urban Grace",
    "Battle Trance",
    "Ghost Wolf",
    "Half-Blood Extraction",
    "Linebreaker",
    "Savage Maw",
    "Blessing Of Luck And Resolve",
    "Blessing Of Luck And Resolve, Mass",
    "Escaping Ward",
    "Fearsome Duplicate",
    "Village Veil",
    "Bestow Insight",
    "Black Mark",
    "Old Salt's Curse",
    "Sacred Space",
    "Truespeak",
    "Veil Of Heaven",
    "Nine Lives",
    "Steal Breath",
    "Blinding Ray",
    "Life Channel",
    "Spawn Ward",
    "Ancestral Regression",
    "Web Bolt",
    "Web Cloud",
    "Gloomblind Bolts",
    "Shadowy Haven",
    "Fire Trail",
    "Mudball",
    "Vomit Twin",
    "Agonizing Rebuke",
    "Chains Of Fire",
    "Death Candle",
    "Firestream",
    "Fury Of The Sun",
    "Healing Warmth",
    "Scorching Ash Form",
    "Touch Of Combustion",
    "Improve Trap",
    "Blood Blaze",
    "Blood Scent",
    "Enemy's Heart",
    "Sentry Skull",
    "Binding Earth",
    "Binding Earth, Mass",
    "Mighty Fist Of The Earth",
    "Raging Rubble",
    "Stone Shield",
    "Alchemical Tinkering",
    "Delay Disease",
    "Sickening Strikes",
    "Absorbing Inhalation",
    "Cloud Shape",
    "Gusting Sphere",
    "Miasmatic Form",
    "Path Of The Winds",
    "Wind Blades",
    "Windy Escape",
    "Commune With Birds",
    "Theft Ward",
    "Winter Feathers",
    "Damnation Stride",
    "Hellmouth Lash",
    "Marid's Mastery",
    "Nereid's Grace",
    "Nixie's Lure",
    "Undine's Curse",
    "Sow Thought",
    "Aboleth's Lung",
    "Fins To Feet",
    "Karmic Blessing",
    "Strong Wings",
    "Imbue With Elemental Might",
    "Earth Glide",
    "Prehensile Pilfer",
    "Squeeze",
    "Shadow Anchor",
    "Blood Money",
    "Covetous Aura",
    "Deathwine",
    "Sign Of Wrath",
    "Swipe",
    "Unconscious Agenda",
    "Ironbloom Sprouts",
    "Bed Of Iron",
    "Carry Companion",
    "Clarion Call",
    "Emblazon Crest",
    "Keep Watch",
    "Serren's Armor Lock",
    "Serren's Swift Girding",
    "Ward Shield",
    "Curse Item",
    "Lissalan Snake Sigil",
    "Display Aversion",
    "Domination Link",
    "Project Weakness",
    "Steal Years",
    "Steal Years, Greater",
    "Transmute Wine To Blood",
    "Winter's Grasp",
    "Irriseni Mirror Sight",
    "Bleed For Your Master",
    "Die For Your Master",
    "Familiar Figment",
    "Hunter's Friend",
    "Scamper",
    "Sea Steed",
    "Sea Stallion",
    "Share Shape",
    "Sky Steed",
    "Flurry Of Snowballs",
    "Snowball",
    "Ice Spears",
    "Martyr's Last Blessing",
    "Peasant Armaments",
    "Conjure Deadfall",
    "Create Holds",
    "Determine Depth",
    "Discern Value",
    "Nature's Ravages",
    "Nature's Ravages, Greater",
    "Corpse Hammer",
    "Oath Of Justice",
    "Tactical Formation",
    "Soothing Word",
    "Frosthammer",
    "Accept Affliction",
    "Angelic Aspect, Lesser",
    "Angelic Aspect, Greater",
    "Angelic Aspect",
    "Archon's Trumpet",
    "Burst Of Radiance",
    "Chains Of Light",
    "Touch Of Mercy",
    "Hymn Of Mercy",
    "Hymn Of Peace",
    "Blood Of The Martyr",
    "Charitable Impulse",
    "Elemental Assessor",
    "Sanctify Weapons",
    "Summon Stampede",
    "Vinetrap",
    "Black Sword Of War",
    "Bloody Tears And Jagged Smile",
    "Blightburn Weapon",
    "Chameleon Scales",
    "Dark-Light",
    "Enlarge Tail",
    "Lead Plating",
    "Shadow Dragon Aspect",
    "Strip Scales",
    "Unseen Engineers",
    "Detect Relations",
    "Business Booms",
    "Prosperous Room",
    "Renovation",
    "Teleport Structure",
    "Bless Army",
    "Imbue Army Special Ability",
    "Tactical Insight",
    "Ceremony",
    "Dragon Turtle Shell",
    "Draconic Suppression",
    "Dragonvoice",
    "Dungeonsight",
    "Erode Defenses",
    "Gravity Well",
    "Heart Of The Mammoth",
    "Illusory Hoard",
    "Kreighton's Perusal",
    "Page-Bound Epiphany",
    "Collaborative Thaumaturgy",
    "Sure Casting",
    "Cauterizing Weapon",
    "Tactical Miscalculation",
    "Wall Of Light",
    "Blood Song",
    "Hallucinogenic Smoke",
    "Jungle Mind",
    "Lay Of The Land",
    "Source Severance",
    "Tectonic Communion",
    "Anti-Summoning Shield",
    "Burst With Light",
    "Detect Demon",
    "Protection From Outsiders",
    "Righteous Blood",
    "Telepathic Censure",
    "Contact Nalfeshnee",
    "Ascension",
    "Bleed Glory",
    "Deathless",
    "Lend Path",
    "Mythic Severance",
    "Restore Mythic Power",
    "Share Glory",
    "Steal Power",
    "Terraform",
    "Apparent Treachery",
    "Film Of Filth",
    "Lightning Lash",
    "Maw Of Chaos",
    "Summon Greater Demon",
    "Summon Lesser Demon",
    "Unleash Pandemonium",
    "Vermicious Assumption",
    "Borrowed Time",
    "Elemental Bombardment",
    "Imbue With Flight",
    "Soulreaver",
    "Sustaining Legend",
    "Accursed Glare",
    "Share Skin",
    "Share Skin, Greater",
    "Heavy Water",
    "Hydrophobia",
    "Blood Boil",
    "Rune Of Jandelay",
    "Bleeding Strike",
    "Reveal Mirage",
    "Storm Of Blades",
    "Summon Genie, Lesser",
    "Summon Genie",
    "Summon Genie, Greater",
    "Inner Focus",
    "Abyssal Vermin",
    "Explosion Of Rot",
    "Antithetical Constraint",
    "Arbitrament",
    "Ardor's Onslaught",
    "Counterbalancing Aura",
    "Dispel Balance",
    "Recentering Drone",
    "Steal Book",
    "Summon Lesser Psychopomp",
    "Summon Vanth",
    "Possession Trap",
    "Sphere Of Warding",
    "Carrion Compass",
    "Empower Holy Water",
    "Force Anchor",
    "Life Shield",
    "Necromantic Burden",
    "Undeath Inversion",
    "Abadar's Truthtelling",
    "Abstemiousness",
    "Baphomet's Blessing",
    "Beacon Of Luck",
    "Blade Snare",
    "Blessing Of The Watch",
    "Brittle Portal",
    "Burst Of Glory",
    "Caustic Blood",
    "Channel The Gift",
    "Channel Vigor",
    "Dead Eye's Arrow",
    "Defending Bone",
    "Dream Feast",
    "Early Judgment",
    "Enhance Water",
    "Face Of The Devourer",
    "Fairness",
    "Fallback Strategy",
    "False Alibi",
    "Firebelly",
    "Fractions Of Heal And Harm",
    "Freedom's Toast",
    "Ghoul Hunger",
    "Gozreh's Trident",
    "Hairline Fractures",
    "Hammer Of Mending",
    "Haze Of Dreams",
    "Hunter's Blessing",
    "Ice Armor",
    "Inheritor's Smite",
    "Light Prison",
    "Lighten Object",
    "Lighten Object, Mass",
    "Lose The Trail",
    "Maddening Oubliette",
    "Monstrous Extremities",
    "Night Of Blades",
    "Pick Your Poison",
    "Plague Bearer",
    "Poisoned Egg",
    "Read Weather",
    "Replenish Ki",
    "Rovagug's Fury",
    "Secret Speech",
    "Seducer's Eyes",
    "Shared Sacrifice",
    "Shield Of The Dawnflower, Greater",
    "Sky Swim",
    "Smite Abomination",
    "Spawn Calling",
    "Spell Gauge",
    "Spell Scourge",
    "Symbol Of Debauchery",
    "Symbol Of Dispelling",
    "Tap Inner Beauty",
    "Touch Of Bloodletting",
    "Tracking Mark",
    "Transplant Visage",
    "Unwelcome Halo",
    "Vengeful Stinger",
    "Vexing Miscalculation",
    "Weapons Against Evil",
    "Create Variant Mummy",
    "Virulence",
    "Calculated Luck",
    "Cleromancy",
    "Lucky Number",
    "Mathematical Curse",
    "Numerological Evocation",
    "Numerological Resistance",
    "Spectral Saluqi",
    "Harrowing, Greater",
    "Abeyance",
    "Aggravate Affliction",
    "Bestow Curse, Greater",
    "Storm Step",
    "Boneshatter",
    "Alter River",
    "Detect Metal",
    "Hanspur's Flotsam Vessel",
    "Magnetic Field",
    "Resounding Clang",
    "Riversight",
    "Sabotage Construct",
    "Antitech Field",
    "Destroy Robot",
    "Detect Radiation",
    "Discharge",
    "Discharge, Greater",
    "Infuse Robot",
    "Irradiate",
    "Magic Circle Against Technology",
    "Make Whole, Greater",
    "Memory Of Function",
    "Protection From Technology",
    "Rebuke Technology",
    "Recharge",
    "Remove Radioactivity",
    "Remove Radioactivity, Greater",
    "Technomancy",
    "Cosmic Ray",
    "Gravity Sphere",
    "Planetarium",
    "Planetary Adaptation",
    "Planetary Adaptation, Mass",
    "Reboot",
    "Starsight",
    "Adhesive Blood",
    "Adhesive Spittle",
    "Adjustable Disguise",
    "Adjustable Polymorph",
    "Aggressive Thundercloud",
    "Aggressive Thundercloud, Greater",
    "Air Geyser",
    "Air Step",
    "Align Weapon, Communal",
    "Alter Musical Instrument",
    "Anchored Step",
    "Animal Purpose Training",
    "Anonymous Interaction",
    "Anti-Incorporeal Shell",
    "Aura Sight",
    "Banshee Blast",
    "Barrow Haze",
    "Beastspeak",
    "Bestow Auras",
    "Blade Lash",
    "Blazing Rainbow",
    "Blessed Fist",
    "Bloatbomb",
    "Blood Armor",
    "Blood Sentinel",
    "Blurred Movement",
    "Body Capacitance",
    "Bullet Ward",
    "Buoyancy",
    "Chameleon Stride, Greater",
    "Climbing Beanstalk",
    "Companion Life Link",
    "Contingent Action",
    "Contingent Scroll",
    "Creeping Ice",
    "Crimson Confession",
    "Curse Of Burning Sleep",
    "Dimensional Bounce",
    "Disable Construct",
    "Discern Next Of Kin",
    "Disguise Weapon",
    "Enchantment Foil",
    "Enemy Insight",
    "Euphoric Cloud",
    "Extreme Flexibility",
    "Eyes Of The Void",
    "Fairy Ring Retreat",
    "Familiar Double",
    "Feast On Fear",
    "Flaming Sphere, Greater",
    "Flexible Fury",
    "Focused Scrutiny",
    "Font Of Spirit Magic",
    "Gentle Breeze",
    "Glue Seal",
    "Guardian Of Faith",
    "Heart Of The Metal",
    "Heightened Awareness",
    "Heightened Reflexes",
    "Hex Glyph",
    "Hex Glyph, Greater",
    "Hex Vulnerability",
    "Holy Ice Weapon",
    "Investigative Mind",
    "Invisibility Alarm",
    "Life Pact",
    "Line In The Sand",
    "Long Arm",
    "Longstrider, Greater",
    "Magnifying Chime",
    "Mantle Of Calm",
    "Marching Chant",
    "Mark Of Obvious Ethics",
    "Memorize Page",
    "Mindlocked Messenger",
    "Mirror Hideaway",
    "Mirror Polish",
    "Mirror Transport",
    "Molten Orb",
    "Monkey Fish",
    "Muffle Sound",
    "Nauseating Dart",
    "Nauseating Trail",
    "Path Of Glory",
    "Path Of Glory, Greater",
    "Persistent Vigor",
    "Phantom Blood",
    "Pierce Disguise",
    "Planeslayer's Call",
    "Polymorph Familiar",
    "Refine Improvised Weapon",
    "Repair Undead",
    "Repair Undead, Mass",
    "River Whip",
    "Sense Spirit Magic",
    "Shield Companion",
    "Shield Of Fortification",
    "Shield Of Fortification, Greater",
    "Sickening Entanglement",
    "Silent Table",
    "Silver Darts",
    "Slowing Mud",
    "Sonic Form",
    "Sonic Scream",
    "Speak With Haunt",
    "Spellcrash, Lesser",
    "Spellcrash, Greater",
    "Spellcrash",
    "Stench Of Prey",
    "Stone Discus",
    "Stricken Heart",
    "Stunning Barrier",
    "Stunning Barrier, Greater",
    "Sunder Breaker",
    "Sundering Shards",
    "Symbol Of Laughter",
    "Thorn Javelin",
    "Thorny Entanglement",
    "Thunderstomp",
    "Thunderstomp, Greater",
    "Time Shudder",
    "Triggered Suggestion",
    "Twilight Haze",
    "Unbearable Brightness",
    "Unholy Ice Weapon",
    "Unliving Rage",
    "Vampiric Shadow Shield",
    "Wall Of Blindness/Deafness",
    "Wall Of Nausea",
    "Wave Shield",
    "Whip Of Spiders",
    "Whip Of Ants",
    "Whip Of Centipedes",
    "Widen Auras",
    "Semblance Of Flesh",
    "Shared Suffering",
    "Wracking Ray",
    "Acid Maw",
    "Arcane Disruption",
    "Blood Salvation",
    "Energy Hack",
    "Imbue Hex",
    "Phantom Hunt",
    "Spirit Call",
    "Wrathful Weapon",
    "Aura Of Cannibalism",
    "Isolate",
    "Control Vermin",
    "Dust Ward",
    "Ironskin",
    "Ice Slick",
    "Magic Boulder",
    "Fleshy Facade",
    "Hungry Earth",
    "Augmenting Wall",
    "Bloody Arrows",
    "Calm Air",
    "Conversing Wind",
    "Rain Of Arrows",
    "Telekinetic Volley",
    "Bouncy Body",
    "Mud Buddy",
    "Endothermic Touch",
    "Scale Spikes",
    "Scale Spikes, Greater",
    "Air Breathing",
    "Blood In The Water",
    "Gift Of The Deep",
    "Spellsteal",
    "Sundered Serpent Coil",
    "Curse Of Unexpected Death",
    "Burdened Thoughts",
    "Hollow Blades",
    "Runic Overload",
    "Siphon Might",
    "Stone Throwing",
    "Steal Size",
    "Twisted Futures",
    "Amplify Stench",
    "Mark Of The Reptile God",
    "Swarm Of Fangs",
    "Transfer Regeneration",
    "Trial Of Fire And Acid",
    "Callback",
    "Callback, Greater",
    "Disrupt Link",
    "Duplicate Familiar",
    "Empathy Conduit",
    "Merge With Familiar",
    "Soulswitch",
    "Transfer Familiar",
    "Beanstalk",
    "Flaming Aura",
    "Frosty Aura",
    "Quick Throwing",
    "Thunderous Footfalls",
    "Thanatotic Fury",
    "Titanic Anchoring",
    "Aura Of Inviolate Ownership",
    "Blade Tutor's Spirit",
    "Darting Duplicate",
    "Dimensional Blade",
    "Fiery Runes",
    "Instant Weapon",
    "Reaper's Coterie",
    "Rubberskin",
    "Umbral Weapon",
    "Vine Strike",
    "Cheetah's Sprint",
    "Clear Grove",
    "Globe Of Tranquil Water",
    "Oasis",
    "Planar Refuge",
    "Raven's Flight",
    "Wild Instinct",
    "Gravel Vortex",
    "Daywalker",
    "Plant Voice",
    "Spore Burst",
    "Alter Summoned Monster",
    "Final Sacrifice",
    "Gird Ally",
    "Instant Restoration",
    "Master's Escape",
    "Master's Mutation",
    "Summon Laborers",
    "Illusory Maze",
    "Make Lost",
    "Mind Maze",
    "Puzzle Box",
    "Stoke The Inner Fire",
    "Akashic Form",
    "Analyze Aura",
    "Anticipate Thoughts",
    "Apport Object",
    "Apport Animal",
    "Aura Alteration",
    "Drain Poison",
    "Garden Of Peril",
    "Invigorating Poison",
    "Neutralize Poison, Greater",
    "Poison Breath",
    "Sword To Snake",
    "Toxic Rupture",
    "Venomous Bite",
    "Blend With Surroundings",
    "Body Double",
    "Grasping Tentacles",
    "Grease, Greater",
    "Hide Weapon",
    "Selective Invisibility",
    "Sense Vitals",
    "Shifting Shadows",
    "Beloved Of The Forge",
    "Blessing Of Liberty",
    "Harmless Form",
    "Harvest Season",
    "Wall Of Clockwork",
    "Cloak Of Secrets",
    "Coin Shot",
    "Ears Of The City",
    "Illusory Crowd",
    "Locksight",
    "Peace Bond",
    "Speak Local Language",
    "Aversion",
    "Awaken Construct",
    "Babble",
    "Bilocation",
    "Burst Of Adrenaline",
    "Burst Of Insight",
    "Call Spirit",
    "Calm Spirit",
    "Catatonia",
    "Charge Object",
    "Cognitive Block",
    "Condensed Ether",
    "Contagious Zeal",
    "Create Mindscape",
    "Create Mindscape, Greater",
    "Decrepit Disguise",
    "Deja Vu",
    "Demand Offering",
    "Detect Mindscape",
    "Detect Psychic Significance",
    "Divide Mind",
    "Dream Council",
    "Dream Scan",
    "Dream Travel",
    "Dream Voyage",
    "Ectoplasmic Eruption",
    "Ectoplasmic Snare",
    "Ego Whip I",
    "Ego Whip II",
    "Ego Whip III",
    "Ego Whip IV",
    "Ego Whip V",
    "Emotive Block",
    "Enshroud Thoughts",
    "Entrap Spirit",
    "Erase Impressions",
    "Ethereal Envelope",
    "Ethereal Envelopment",
    "Ethereal Fists",
    "Etheric Shards",
    "Explode Head",
    "Foster Hatred",
    "Ghost Whip",
    "Grave Words",
    "Hypercognition",
    "Id Insinuation I",
    "Id Insinuation II",
    "Id Insinuation III",
    "Id Insinuation IV",
    "Implant False Reading",
    "Incorporeal Chains",
    "Inflict Pain",
    "Inflict Pain, Mass",
    "Instigate Psychic Duel",
    "Intellect Fortress I",
    "Intellect Fortress II",
    "Intellect Fortress III",
    "Mental Barrier I",
    "Mental Barrier II",
    "Mental Barrier III",
    "Mental Barrier IV",
    "Mental Barrier V",
    "Mental Block",
    "Microcosm",
    "Mind Probe",
    "Mind Swap",
    "Mind Swap, Major",
    "Mind Thrust I",
    "Mind Thrust II",
    "Mind Thrust III",
    "Mind Thrust IV",
    "Mind Thrust V",
    "Mind Thrust VI",
    "Mindlink",
    "Mindscape Door",
    "Mindwipe",
    "Node Of Blasting",
    "Object Possession",
    "Object Possession, Greater",
    "Object Possession, Lesser",
    "Object Reading",
    "Oneiric Horror",
    "Oneiric Horror, Greater",
    "Paranoia",
    "Parchment Swarm",
    "Placebo Effect",
    "Possession",
    "Possession, Greater",
    "Primal Regression",
    "Psychic Asylum",
    "Psychic Crush I",
    "Psychic Crush II",
    "Psychic Crush III",
    "Psychic Crush IV",
    "Psychic Crush V",
    "Psychic Image",
    "Psychic Reading",
    "Psychic Surgery",
    "Purge Spirit",
    "Quintessence",
    "Remote Viewing",
    "Repress Memory",
    "Retrocognition",
    "Riding Possession",
    "Sealed Life",
    "Sealed Life, Greater",
    "Sessile Spirit",
    "Shadow Body",
    "Spirit-Bound Blade",
    "Synapse Overload",
    "Synaptic Pulse",
    "Synaptic Pulse, Greater",
    "Synaptic Scramble",
    "Synesthesia",
    "Synesthesia, Mass",
    "Talismanic Implement",
    "Telekinetic Maneuver",
    "Telekinetic Projectile",
    "Telekinetic Storm",
    "Telempathic Projection",
    "Telepathy",
    "Thaumaturgic Circle",
    "Thought Echo",
    "Thought Shield I",
    "Thought Shield II",
    "Thought Shield III",
    "Thought Shield IV",
    "Thought Shield V",
    "Thoughtsense",
    "Tower Of Iron Will I",
    "Tower Of Iron Will II",
    "Tower Of Iron Will III",
    "Tower Of Iron Will IV",
    "Tower Of Iron Will V",
    "Unshakable Zeal",
    "Wall Of Ectoplasm",
    "Withdraw Affliction",
    "Air Of Authority",
    "Bleaching Resistance",
    "Burn Corruption",
    "Champion's Bout",
    "Damnation Of Memory",
    "Elemental Mastery",
    "Fable Tapestry",
    "Fire's Friend",
    "Fleshwarping Swarm",
    "Lament Of Summer's Last Breath",
    "Lost Passage",
    "Lost Locale",
    "Mantle Of The Magic Warriors",
    "Martial Telekinesis",
    "Miasmal Dread",
    "Murderous Crow",
    "Overlook",
    "Probe History",
    "Respectful Quiet",
    "Shadow Of Doubt",
    "Siege Scatter",
    "Summon Giant Ally I",
    "Summon Giant Ally II",
    "Summon Giant Ally III",
    "Summon Kami",
    "Suppressing Stone",
    "Wall Of Brine",
    "Zephyr's Fleetness",
    "Create Drug",
    "Death Pact",
    "Fool's Teleport",
    "Implanted Projection",
    "Dream Shield",
    "Jealous Rage",
    "Mindshock",
    "Psychic Leech",
    "Quell Energy",
    "Retributive Reparations",
    "Sensory Amplifier",
    "Subjective Reality",
    "Ectoplasmic Hand",
    "Mantle Of Doubt",
    "Mind Over Matter",
    "Out Of Sight",
    "Phantom Limb",
    "Psychonaut Manifestation",
    "Alleviate Addiction",
    "Contact High",
    "Imbue With Addiction",
    "Night Blindness",
    "Pesh Vigor",
    "Compel Tongue",
    "Compel Tongue, Mass",
    "Fleeting Memory",
    "Fleeting Memory, Mass",
    "Secret Sign",
    "Venomous Promise",
    "Arcane Pocket",
    "Vacuous Vessel",
    "Adroit Retrieval",
    "Authenticating Gaze",
    "Curse Of Keeping",
    "Evaluator's Lens",
    "Fleeting Defect",
    "Incendiary Runes",
    "Peerless Integrity",
    "Remarkable Legerdemain",
    "Secret Coffer",
    "Secret Vault",
    "Shadow Enchantment",
    "Shadow Enchantment, Greater",
    "Detect Fiendish Presence",
    "Devil Snare",
    "Punishing Armor",
    "Unholy Ward",
    "Blood Tentacles",
    "Caustic Safeguard",
    "Coward's Cowl",
    "Dream Dalliance",
    "Enticing Adulation",
    "Furious Fire Barrage",
    "Golden Guise",
    "Shadow Endurance",
    "Seer's Bane",
    "Aroden's Magic Army",
    "Aroden's Spellsword",
    "Banishing Blade",
    "Create Armaments",
    "Expeditious Construction",
    "Force Sword",
    "Grand Destiny",
    "Guardian Monument, Lesser",
    "Guardian Monument, Greater",
    "Human Potential",
    "Human Potential, Mass",
    "Last Azlanti's Defending Sword",
    "Last Azlanti's Defending Sword, Mass",
    "Linked Legacy",
    "Splinter Spell Resistance",
    "Winged Sword",
    "Celestial Healing",
    "Celestial Healing, Greater",
    "Cyclic Reincarnation",
    "Jatembe's Ire",
    "Artificer's Curse",
    "Deft Digits",
    "Dissolution",
    "Emblem Of Greed",
    "Full Pouch",
    "Legendary Proportions",
    "Liquefy",
    "Open Arms",
    "Rags To Riches",
    "Rune Of Ruin",
    "Tears To Wine",
    "Transmute Golem",
    "Find Fault",
    "Foretell Failure",
    "Perfect Placement",
    "Heckle",
    "Stage Fright",
    "Tough Crowd",
    "First World Revisions",
    "Darkvault",
    "Fear The Sun",
    "Ignoble Form",
    "Shadowmind",
    "Umbral Strike",
    "Dancing Darkness",
    "Motes Of Dusk And Dawn",
    "Mydriatic Spontaneity",
    "Mydriatic Spontaneity, Mass",
    "Penumbral Disguise",
    "Shield Of Darkness",
    "Spotlight",
    "Touch Of Blindness",
    "Wall Of Split Illumination",
    "Baleful Shadow Transmutation",
    "Masochistic Shadow",
    "Shadow Transmutation",
    "Shadow Transmutation, Greater",
    "Shadow Trap",
    "Shadowform",
    "Umbral Infusion",
    "Umbral Infusion, Mass",
    "Absolution",
    "Aerial Tracks",
    "Animal Ambassador",
    "Aphasia",
    "Auditory Hallucination",
    "Audiovisual Hallucination",
    "Aura Of The Unremarkable",
    "Bountiful Banquet",
    "Break, Greater",
    "Build Trust",
    "Charm Person, Mass",
    "Codespeak",
    "Complex Hallucination",
    "Compulsive Liar",
    "Conditional Curse",
    "Conditional Favor",
    "Conjuration Foil",
    "Conjure Carriage",
    "Contingent Venom",
    "Controlled Fireball",
    "Crime Of Opportunity",
    "Crime Wave",
    "Cultural Adaptation",
    "Curse Of The Outcast",
    "Dark Whispers",
    "Deadman's Contingency",
    "Deceitful Veneer",
    "Deflect Blame",
    "Demanding Message",
    "Demanding Message, Mass",
    "Desperate Weapon",
    "Detect Anxieties",
    "Detect Desires",
    "Detect Magic, Greater",
    "Detect The Faithful",
    "Disrupt Silence",
    "Dress Corpse",
    "Entice Fey",
    "Entice Fey, Greater",
    "Entice Fey, Lesser",
    "Fabricate Disguise",
    "False Belief",
    "False Future",
    "False Resurrection",
    "False Resurrection, Greater",
    "False Vision, Greater",
    "Ghost Brand",
    "Glimpse Of Truth",
    "Handy Grapnel",
    "Hidden Presence",
    "Hollow Heroism",
    "Hollow Heroism, Greater",
    "Illusion Of Treachery",
    "Illusion Of Treachery, Greater",
    "Insect Spies",
    "Insect Spies, Greater",
    "Instant Fake",
    "Instant Summons, Greater",
    "Know Peerage",
    "Languid Venom",
    "Life Of Crime",
    "Mage's Decree",
    "Magic Aura, Greater",
    "Majestic Image",
    "Matchmaker",
    "Meticulous Match",
    "Obscure Poison",
    "Open And Shut",
    "Open Book",
    "Overwhelming Poison",
    "Pack Empathy",
    "Peacebond, Greater",
    "Permanent Hallucination",
    "Phantasmal Affliction",
    "Pocketful Of Vipers",
    "Poisonous Balm",
    "Pox Of Rumors",
    "Prognostication",
    "Quieting Weapons",
    "Red Hand Of The Killer",
    "Reincarnate Spy",
    "Resplendent Mansion",
    "Rumormonger",
    "Scripted Hallucination",
    "Selective Alarm",
    "Shamefully Overdressed",
    "Shifted Steps",
    "Swallow Poison",
    "They Know",
    "Trace Teleport",
    "Trade Items",
    "Treacherous Teleport",
    "Triggered Hallucination",
    "True Prognostication",
    "Underbrush Decoy",
    "Undetectable Trap",
    "Unerring Tracker",
    "Urban Step",
    "Vicarious View",
    "Voluminous Vocabulary",
    "Wizened Appearance",
    "Guardian Armor",
    "Revenant Armor",
    "Shield Of Shards",
    "Spiritual Squire",
    "Bone Fists",
    "Flash Forward",
    "Particulate Form",
    "Phasic Challenge",
    "Spellcurse",
    "Warp Metal",
    "Biting Words",
    "Bouncing Bomb Admixture",
    "Release The Hounds",
    "Roaming Pit",
    "Wall Of Bone",
    "Akashic Communion",
    "Bind Sage",
    "Secluded Grimoire",
    "Alaznist's Jinx",
    "Flexile Curse",
    "Irregular Size",
    "Itching Curse",
    "Kalistocrat's Nightmare",
    "Lost Legacy",
    "Earsend",
    "Hidden Blades",
    "Impenetrable Veil",
    "Innocuous Shape",
    "Nondetection, Lesser",
    "Phantasmal Reminder",
    "Symbol Of Distraction",
    "Touch Of Slumber",
    "Apathy",
    "Assumed Likeness",
    "Calistria's Guardian Wasps",
    "Commune With Texts",
    "Daggermark's Exchange",
    "Diminished Detection",
    "Dongun Shaper's Touch",
    "Dream Reality",
    "Implant Urge",
    "Inveigle Monster",
    "Inveigle Person",
    "Nex's Secret Workshop",
    "Oath Of Anonymity",
    "Recorporeal Incarnation",
    "Rotting Alliance",
    "Sealed Sending",
    "Searching Shadows",
    "Seeds Of Influence",
    "Seeds Of Influence, Greater",
    "Seek Shelter",
    "Substitute Trail",
    "Transfiguring Touch",
    "True Skill",
    "Violent Accident",
    "Wandering Trail",
    "Heretic's Tongue",
    "Watchful Animal",
    "Trial By Fire",
    "Claim Identity",
    "Claim Identity, Greater",
    "Egorian Diplomacy",
    "Garrulous Grin",
    "Insect Scouts",
    "Passing Fancy",
    "Passing Fancy, Mass",
    "Scribe's Binding",
    "Apsu's Shining Scales",
    "Dahak's Release",
    "Draconic Ally",
    "Draconic Malice",
    "Form Of The Alien Dragon I",
    "Form Of The Alien Dragon II",
    "Form Of The Alien Dragon III",
    "Form Of The Exotic Dragon I",
    "Form Of The Exotic Dragon II",
    "Form Of The Exotic Dragon III",
    "Hermean Potential",
    "Scales Of Deflection",
    "Tail Strike",
    "Absurdity",
    "Alleviate Corruption",
    "Appearance Of Life",
    "Assume Appearance",
    "Assume Appearance, Greater",
    "Ban Corruption",
    "Barbed Chains",
    "Blood Ties",
    "Bloodbath",
    "Boneshaker",
    "Borrow Corruption",
    "Charnel House",
    "Compelling Rant",
    "Contact Entity I",
    "Contact Entity II",
    "Contact Entity III",
    "Contact Entity IV",
    "Cruel Jaunt",
    "Curse Of Fell Seasons",
    "Curse Of Night",
    "Curse Terrain, Lesser",
    "Curse Terrain",
    "Curse Terrain, Greater",
    "Curse Terrain, Supreme",
    "Damnation",
    "Death Clutch",
    "Decapitate",
    "Decollate",
    "Dreadscape",
    "Flesh Puppet",
    "Flesh Puppet Horde",
    "Flesh Wall",
    "Flickering Lights",
    "Grasping Corpse",
    "Green Caress",
    "Hedging Weapons",
    "Holy Javelin",
    "Horrific Doubles",
    "Hunger For Flesh",
    "Hunger For Flesh, Mass",
    "Impossible Angles",
    "Life Blast",
    "Locate Gate",
    "Mad Sultan's Melody",
    "Massacre",
    "Maze Of Madness And Suffering",
    "Night Terrors",
    "Pessimism",
    "Phantasmal Asphyxiation",
    "Phantasmal Putrefaction",
    "Phobia",
    "Plundered Power",
    "Profane Nimbus",
    "Pyrotechnic Eruption",
    "Quick Change",
    "Rigor Mortis",
    "Sacramental Seal",
    "Sacred Nimbus",
    "Screaming Flames",
    "Sense Fear",
    "Sense Madness",
    "Sleepwalking Suggestion",
    "Slough",
    "Stave Off Corruption",
    "Straitjacket",
    "Symbol Of Exsanguination",
    "Temporary Graft",
    "Torpid Reanimation",
    "Verminous Transformation",
    "Vile Dog Transformation",
    "Waves Of Blood",
    "Wither Limb",
    "Besmara's Grasping Depths",
    "Crafter's Nightmare",
    "Frigid Souls",
    "Grim Stalker",
    "Horrifying Visage",
    "Mischievous Shadow",
    "Skin Tag",
    "Unsettling Presence",
    "Urgathoa's Beacon",
    "Yellow Sign",
    "Janni's Jaunt",
    "Medusa's Bane",
    "Enlightened Step",
    "Firewalker's Meditation",
    "Rite Of Bodily Purity",
    "Rite Of Centered Mind",
    "See Beyond",
    "Spirit Bonds",
    "Visualization Of The Body",
    "Visualization Of The Mind",
    "Bereave",
    "Overstimulate",
    "Scarify",
    "Shroud Of Darkness",
    "Ferment",
    "Free Spirit",
    "Knock, Mass",
    "Spirit Share",
    "Soul Vault",
    "True Appraisal",
    "Funereal Weapon",
    "Necrostasis",
    "Preserve",
    "Spiral Ascent",
    "Spiral Descent",
    "Betraying Sting",
    "Harvest Knowledge",
    "Incessant Buzzing",
    "Painful Revelation",
    "Pillow Talk",
    "Reveal Secrets",
    "Sadomasochism",
    "Infuse Decay",
    "Unlock Flesh",
    "Bit Of Luck",
    "Curse Of Befouled Fortune",
    "Pouncing Fury",
    "Batrachian Surge",
    "Sweat Poison",
    "Contagious Suggestion",
    "Gullibility",
    "Hypnotism, Greater",
    "Metabolic Molting",
    "Naga Shape I",
    "Naga Shape II",
    "Naga Shape III",
    "Depilate",
    "Fumblestep",
    "Lightfingers",
    "Amnesia",
    "Appearance Of Life, Greater",
    "Covetous Urge",
    "Hide Bruises",
    "Resist Starvation",
    "Beacon Of Guilt",
    "Escape Alarm",
    "Outbreak",
    "Virulent Miasma",
    "Cloak Of Shadows",
    "Shadow Claws",
    "Shadow Jaunt",
    "Shield Of Wings",
    "Charm Fey",
    "Fey Gate",
    "Hold Fey",
    "Iron Stake",
    "Locate Portal",
    "Planar Orientation",
    "Fool's Gold",
    "Burning Entanglement",
    "Nature's Paths",
    "Sand Table",
    "Dousing Rain",
    "Reinvigorating Wind",
    "Steady Saddle",
    "Wicker Horse",
    "Book Ward",
    "Questing Stone",
    "Revelation",
    "Scrivener's Chant",
    "Cursed Treasure",
    "Rotgut",
    "Walk The Plank",
    "Hobble",
    "Hoodwink",
    "Geomessage",
    "Protection From Spores",
    "What Grows Within",
    "Litany Of Truth",
    "Balance Of Suffering",
    "Curative Distillation",
    "Healing Flames",
    "Healing Token",
    "Inspiring Recovery",
    "Purify Body",
    "Befuddled Combatant",
    "Enchantment Sight",
    "Reveal Emotions",
    "Shroud Of Innocuity",
    "Speechreader's Sight",
    "False Face",
    "Perceive Betrayal",
    "Pierce Facade",
    "Aura Of Distraction",
    "Burst Of Force",
    "Debilitating Pain",
    "Debilitating Pain, Mass",
    "Glimpse Of The Akashic",
    "Reflexive Barrier",
    "Rend Body I",
    "Rend Body II",
    "Rend Body III",
    "Rend Body IV",
    "Sensory Overload",
    "Telekinetic Strikes",
    "Thought Worm I",
    "Thought Worm II",
    "Thought Worm III",
    "Thought Worm IV",
    "Ja Noi Aspect",
    "Opportunistic Loyalty",
    "Spectral Scout",
    "Sylvan Hideaway",
    "Diminish Resistance",
    "Guarding Knowledge",
    "Huntmaster's Spear",
    "Protection From Natural Attacks",
    "Repugnant Taste",
    "Barghest Feast",
    "Hobbling Bomb Admixture",
    "Grasp",
    "Mage's Crawl Space",
    "Rock Whip",
    "Shadowfade",
    "Skyshroud",
    "Concealed Breath",
    "Morning Sun",
    "Pale Flame",
    "Radiation Ward",
    "Animus Mine",
    "Animus Mine, Greater",
    "Entomb",
    "Intensify Psyche",
    "Surface Excursion",
    "Cold Iron Fetters",
    "Iron Spine",
    "Mortal Terror",
    "Alluring Spores",
    "Strand Of The Tangled Knot",
    "Thirsting Entanglement",
    "Threefold Face",
    "Threefold Form",
    "Threefold Sight",
    "Ally Across Time",
    "Army Across Time",
    "Temporal Divergence",
    "Temporal Regression",
    "Blade Of Light",
    "Burning Sands",
    "Cleansing Fire",
    "Sun's Disdain",
    "Sun's Disdain, Mass",
    "Sunstalker",
    "Aldori Alacrity",
    "Contest Of Skill",
    "Deivon's Parry",
    "Tactical Adaptation",
    "Tieldlara's Feint",
    "Deceptive Redundancy",
    "Haunting Reminder",
    "Obscured Script",
    "Sympathetic Aura",
    "Fungal Blisters",
    "Sebaceous Twin",
    "Allied Cloak",
    "Billowing Skirt",
    "Grappling Scarf",
    "Restful Cloak",
    "Sculpted Cape",
    "Surefoot Boots",
    "Aquatic Trail",
    "Extreme Buoyancy",
    "Free Swim",
    "Invisibility Bubble",
    "Invisibility Bubble, Giant",
    "Invisibility Bubble, Mass",
    "Lead Anchor",
    "Life Current",
    "Neutral Buoyancy",
    "Pressure Adaptation",
    "Stabilize Pressure",
    "Steam Ray Fusillade",
    "Unlife Current",
    "Wave Form",
    "Absorb Rune I",
    "Absorb Rune II",
    "Absorb Rune III",
    "Hidden Knowledge",
    "Rune Trace",
    "Rune Of Rule",
    "Slave To Sin",
    "Detect Charm",
    "Summon Flight Of Eagles",
    "Suppress Charms And Compulsions",
    "Brand Of Conformity",
    "Brand Of Hobbling",
    "Brand Of Tracking",
    "Dirge Of The Victorious Knights",
    "Infernal Challenger",
    "Shackle",
    "Brightest Light",
    "Detoxify",
    "Preserve Grace",
    "Mask From Divination",
    "Planar Inquiry",
    "Frost Mammoth",
    "Invoke Primal Power",
    "Bone Flense",
    "Crimson Breath",
    "Mark Of Blood",
    "Mirror Mantis",
    "Sarzari Shadow Memory",
    "Sawtooth Terrain",
    "Instant Portrait",
    "Wall Of Silver",
    "Storm Sight"
  ];

  function get(options) {
    var defaultOptions = {
      name: false,
      index: false,
      full: false
    };
    if (options) {
      var defaultOptions = helper.applyOptions(defaultOptions, options);
    };
    var mached = [];
    var _checkForSepllName = function() {
      _all_spellName.forEach(function(arrayItem, index) {
        if (arrayItem.toLowerCase().includes(options.name.toLowerCase())) {
          var object = {
            index: index,
            name: arrayItem
          };
          mached.push(object);
        };
      });
    };
    if (options.name || options.index) {
      if (options.name) {
        _checkForSepllName();
        if (mached.length > 0) {
          if (options.full) {
            return _get_spellsObject({
              array: mached
            });
          } else {
            return mached;
          };
        } else {
          return false
        };
      } else if (options.index) {
        return _get_spellsObject({
          index: options.index
        });
      };
    } else {
      return false;
    };
  };


  function _get_spellsObject(options) {
    var defaultOptions = {
      array: false,
      index: false
    };
    if (options) {
      var defaultOptions = helper.applyOptions(defaultOptions, options);
    };
    var _findSpells = function() {
      if (options.array) {
        var spellsObject = [];
        options.array.forEach(function(arrayItem) {
          spellsObject.push(_all_spellsObject[arrayItem.index]);
        });
        return spellsObject;
      } else if (options.index) {
        return _all_spellsObject[options.index];
      } else {
        return false;
      };
    };
    if (_all_spellsObject != null) {
      return _findSpells();
    } else {
      return false;
    };
  };

  function load() {
    var _cleanUpSpellObject = function(arrayItem) {
      // school
      var tempSchool = {};
      tempSchool.base = arrayItem.school;
      tempSchool.subschool = arrayItem.subschool;
      // add
      arrayItem.school = tempSchool;
      // remove
      delete arrayItem.subschool;

      // descriptors
      var tempDescriptor = {};
      tempDescriptor.acid = arrayItem.acid;
      tempDescriptor.air = arrayItem.air;
      tempDescriptor.chaotic = arrayItem.chaotic;
      tempDescriptor.cold = arrayItem.cold;
      tempDescriptor.curse = arrayItem.curse;
      tempDescriptor.darkness = arrayItem.darkness;
      tempDescriptor.death = arrayItem.death;
      tempDescriptor.disease = arrayItem.disease;
      tempDescriptor.earth = arrayItem.earth;
      tempDescriptor.electricity = arrayItem.electricity;
      tempDescriptor.emotion = arrayItem.emotion;
      tempDescriptor.evil = arrayItem.evil;
      tempDescriptor.fear = arrayItem.fear;
      tempDescriptor.fire = arrayItem.fire;
      tempDescriptor.force = arrayItem.force;
      tempDescriptor.good = arrayItem.good;
      tempDescriptor.language_dependent = arrayItem.language_dependent;
      tempDescriptor.lawful = arrayItem.lawful;
      tempDescriptor.light = arrayItem.light;
      tempDescriptor.mind_affecting = arrayItem.mind_affecting;
      tempDescriptor.pain = arrayItem.pain;
      tempDescriptor.poison = arrayItem.poison;
      tempDescriptor.shadow = arrayItem.shadow;
      tempDescriptor.sonic = arrayItem.sonic;
      tempDescriptor.water = arrayItem.water;
      tempDescriptor.ruse = arrayItem.ruse;
      tempDescriptor.meditative = arrayItem.meditative;
      for (var key in tempDescriptor) {
        if (tempDescriptor[key] == "1") {
          tempDescriptor[key] = true;
        } else {
          tempDescriptor[key] = false;
        };
      };
      tempDescriptor.string = arrayItem.descriptor;
      // add
      arrayItem.descriptor = tempDescriptor;
      // remove
      delete arrayItem.acid;
      delete arrayItem.air;
      delete arrayItem.chaotic;
      delete arrayItem.cold;
      delete arrayItem.curse;
      delete arrayItem.darkness;
      delete arrayItem.death;
      delete arrayItem.disease;
      delete arrayItem.earth;
      delete arrayItem.electricity;
      delete arrayItem.emotion;
      delete arrayItem.evil;
      delete arrayItem.fear;
      delete arrayItem.fire;
      delete arrayItem.force;
      delete arrayItem.good;
      delete arrayItem.language_dependent;
      delete arrayItem.lawful;
      delete arrayItem.light;
      delete arrayItem.mind_affecting;
      delete arrayItem.pain;
      delete arrayItem.poison;
      delete arrayItem.shadow;
      delete arrayItem.sonic;
      delete arrayItem.water;
      delete arrayItem.ruse;
      delete arrayItem.meditative;

      // description
      var tempDescription = {};
      tempDescription.effect = arrayItem.effect;
      tempDescription.short = arrayItem.short_description;
      tempDescription.plain = arrayItem.description;
      tempDescription.formated = arrayItem.description_formated;
      // add
      arrayItem.description = tempDescription;
      // remove
      delete arrayItem.effect;
      delete arrayItem.description_formated;
      delete arrayItem.short_description;

      // mythic
      var tempMythic = {};
      if (arrayItem.mythic == "1") {
        tempMythic.mythic = true;
      } else {
        tempMythic.mythic = false;
      };
      tempMythic.text = arrayItem.mythic_text;
      tempMythic.augmented = arrayItem.augmented;
      // add
      arrayItem.mythic = tempMythic;
      // remove
      delete arrayItem.mythic_text;
      delete arrayItem.augmented;

      // level
      var tempLevel = {};
      tempLevel.sla = arrayItem.SLA_Level;
      tempLevel.sorcerer = arrayItem.sorcerer;
      tempLevel.wizard = arrayItem.wizard;
      tempLevel.cleric = arrayItem.cleric;
      tempLevel.druid = arrayItem.druid;
      tempLevel.ranger = arrayItem.ranger;
      tempLevel.bard = arrayItem.bard;
      tempLevel.paladin = arrayItem.paladin;
      tempLevel.alchemist = arrayItem.alchemist;
      tempLevel.summoner = arrayItem.summoner;
      tempLevel.witch = arrayItem.witch;
      tempLevel.inquisitor = arrayItem.inquisitor;
      tempLevel.oracle = arrayItem.oracle;
      tempLevel.antipaladin = arrayItem.antipaladin;
      tempLevel.magus = arrayItem.magus;
      tempLevel.adept = arrayItem.adept;
      tempLevel.bloodrager = arrayItem.bloodrager;
      tempLevel.shaman = arrayItem.shaman;
      tempLevel.psychic = arrayItem.psychic;
      tempLevel.medium = arrayItem.medium;
      tempLevel.mesmerist = arrayItem.mesmerist;
      tempLevel.occultist = arrayItem.occultist;
      tempLevel.spiritualist = arrayItem.spiritualist;
      tempLevel.skald = arrayItem.skald;
      tempLevel.investigator = arrayItem.investigator;
      tempLevel.hunter = arrayItem.hunter;
      for (var key in tempLevel) {
        if (!isNaN(parseInt(tempLevel[key], 10))) {
          tempLevel[key] = parseInt(tempLevel[key], 10);
        } else {
          tempLevel[key] = null;
        };
      };
      tempLevel.string = arrayItem.spell_level;
      // add
      arrayItem.level = tempLevel;
      // remove
      delete arrayItem.spell_level;
      delete arrayItem.SLA_Level;
      delete arrayItem.sorcerer;
      delete arrayItem.wizard;
      delete arrayItem.cleric;
      delete arrayItem.druid;
      delete arrayItem.ranger;
      delete arrayItem.bard;
      delete arrayItem.paladin;
      delete arrayItem.alchemist;
      delete arrayItem.summoner;
      delete arrayItem.witch;
      delete arrayItem.inquisitor;
      delete arrayItem.oracle;
      delete arrayItem.antipaladin;
      delete arrayItem.magus;
      delete arrayItem.adept;
      delete arrayItem.bloodrager;
      delete arrayItem.shaman;
      delete arrayItem.psychic;
      delete arrayItem.medium;
      delete arrayItem.mesmerist;
      delete arrayItem.occultist;
      delete arrayItem.spiritualist;
      delete arrayItem.skald;
      delete arrayItem.investigator;
      delete arrayItem.hunter;

      // components
      var tempComponents = {};
      tempComponents.verbal = arrayItem.verbal;
      tempComponents.somatic = arrayItem.somatic;
      tempComponents.material = arrayItem.material;
      tempComponents.focus = arrayItem.focus;
      tempComponents.divine_focus = arrayItem.divine_focus;
      tempComponents.costly = arrayItem.costly_components;
      for (var key in tempComponents) {
        if (tempComponents[key] == "1") {
          tempComponents[key] = true;
        } else {
          tempComponents[key] = false;
        };
      };
      if (arrayItem.material_costs != "NULL") {
        tempComponents.cost = parseInt(arrayItem.material_costs, 10);
      } else {
        tempComponents.cost = 0;
      };
      tempComponents.string = arrayItem.components;
      // add
      arrayItem.components = tempComponents
      // remove
      delete arrayItem.verbal;
      delete arrayItem.somatic;
      delete arrayItem.material;
      delete arrayItem.focus;
      delete arrayItem.divine_focus;
      delete arrayItem.costly_components;
      delete arrayItem.material_costs;

      // casting
      var tempCasting = {};
      if (arrayItem.dismissible == "1") {
        tempCasting.dismissible = true;
      } else {
        tempCasting.dismissible = false;
      };
      if (arrayItem.shapeable == "1") {
        tempCasting.shapeable = true;
      } else {
        tempCasting.shapeable = false;
      };
      tempCasting.saving = arrayItem.saving_throw;
      tempCasting.spell_resistence = arrayItem.spell_resistence;
      tempCasting.targets = arrayItem.targets;
      tempCasting.time = arrayItem.casting_time;
      tempCasting.range = arrayItem.range;
      tempCasting.area = arrayItem.area;
      tempCasting.duration = arrayItem.duration;
      // add
      arrayItem.casting = tempCasting
      // remove
      delete arrayItem.spell_resistence;
      delete arrayItem.targets;
      delete arrayItem.shapeable;
      delete arrayItem.dismissible;
      delete arrayItem.saving_throw;
      delete arrayItem.casting_time;
      delete arrayItem.range;
      delete arrayItem.area;
      delete arrayItem.duration;

      // groups
      var tempGroups = {};
      tempGroups.domain = arrayItem.domain;
      tempGroups.patron = arrayItem.patron;
      tempGroups.bloodline = arrayItem.bloodline;
      // add
      arrayItem.groups = tempGroups
      // remove
      delete arrayItem.domain;
      delete arrayItem.patron;
      delete arrayItem.bloodline;
    };
    var _get_allSpells = function(data) {
      _all_spellsObject = helper.csvToJSON(data);
      // clean up spell objects
      _all_spellsObject.forEach(function(arrayItem) {
        _cleanUpSpellObject(arrayItem);
      });
      // console.log("spell data loaded");
    };
    helper.loadCsv("../db/spells.csv", function(data) {
      _get_allSpells(data);
    });
  };

  // exposed methods
  return {
    load: load,
    get: get
  };

})();
